// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anttweak.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "anttweak.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace anttweak {

namespace {


}  // namespace


void protobuf_AssignDesc_anttweak_2eproto() {
  protobuf_AddDesc_anttweak_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "anttweak.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_anttweak_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_anttweak_2eproto() {
}

void protobuf_AddDesc_anttweak_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2fdescriptor_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016anttweak.proto\022\010anttweak\032 google/proto"
    "buf/descriptor.proto:0\n\007color3f\022\035.google"
    ".protobuf.FieldOptions\030\320\206\003 \001(\010:0\n\007color4"
    "f\022\035.google.protobuf.FieldOptions\030\321\206\003 \001(\010"
    ":.\n\005dir3f\022\035.google.protobuf.FieldOptions"
    "\030\322\206\003 \001(\010:/\n\006nobind\022\035.google.protobuf.Fie"
    "ldOptions\030\323\206\003 \001(\010:-\n\004minF\022\035.google.proto"
    "buf.FieldOptions\030\324\206\003 \001(\002:-\n\004maxF\022\035.googl"
    "e.protobuf.FieldOptions\030\325\206\003 \001(\002:.\n\005stepF"
    "\022\035.google.protobuf.FieldOptions\030\326\206\003 \001(\002:"
    "-\n\004minI\022\035.google.protobuf.FieldOptions\030\327"
    "\206\003 \001(\005:-\n\004maxI\022\035.google.protobuf.FieldOp"
    "tions\030\330\206\003 \001(\005:.\n\005stepI\022\035.google.protobuf"
    ".FieldOptions\030\331\206\003 \001(\005", 541);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "anttweak.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    50000, 8, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    50001, 8, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    50002, 8, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    50003, 8, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    50004, 2, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    50005, 2, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    50006, 2, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    50007, 5, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    50008, 5, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    50009, 5, false, false);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_anttweak_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_anttweak_2eproto {
  StaticDescriptorInitializer_anttweak_2eproto() {
    protobuf_AddDesc_anttweak_2eproto();
  }
} static_descriptor_initializer_anttweak_2eproto_;
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  color3f(kColor3FFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  color4f(kColor4FFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  dir3f(kDir3FFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  nobind(kNobindFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< float >, 2, false >
  minF(kMinFFieldNumber, 0);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< float >, 2, false >
  maxF(kMaxFFieldNumber, 0);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< float >, 2, false >
  stepF(kStepFFieldNumber, 0);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  minI(kMinIFieldNumber, 0);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  maxI(kMaxIFieldNumber, 0);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  stepI(kStepIFieldNumber, 0);

// @@protoc_insertion_point(namespace_scope)

}  // namespace anttweak

// @@protoc_insertion_point(global_scope)
