// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generator.proto

#ifndef PROTOBUF_generator_2eproto__INCLUDED
#define PROTOBUF_generator_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "anttweak.pb.h"
// @@protoc_insertion_point(includes)

namespace generator {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_generator_2eproto();
void protobuf_AssignDesc_generator_2eproto();
void protobuf_ShutdownFile_generator_2eproto();

class Config;

// ===================================================================

class Config : public ::google::protobuf::Message {
 public:
  Config();
  virtual ~Config();

  Config(const Config& from);

  inline Config& operator=(const Config& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Config& default_instance();

  void Swap(Config* other);

  // implements Message ----------------------------------------------

  Config* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Config& from);
  void MergeFrom(const Config& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float length = 1;
  inline bool has_length() const;
  inline void clear_length();
  static const int kLengthFieldNumber = 1;
  inline float length() const;
  inline void set_length(float value);

  // optional float width = 2;
  inline bool has_width() const;
  inline void clear_width();
  static const int kWidthFieldNumber = 2;
  inline float width() const;
  inline void set_width(float value);

  // optional float height = 3;
  inline bool has_height() const;
  inline void clear_height();
  static const int kHeightFieldNumber = 3;
  inline float height() const;
  inline void set_height(float value);

  // optional uint32 height_segments = 4;
  inline bool has_height_segments() const;
  inline void clear_height_segments();
  static const int kHeightSegmentsFieldNumber = 4;
  inline ::google::protobuf::uint32 height_segments() const;
  inline void set_height_segments(::google::protobuf::uint32 value);

  // optional uint32 radial_segments = 5;
  inline bool has_radial_segments() const;
  inline void clear_radial_segments();
  static const int kRadialSegmentsFieldNumber = 5;
  inline ::google::protobuf::uint32 radial_segments() const;
  inline void set_radial_segments(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:generator.Config)
 private:
  inline void set_has_length();
  inline void clear_has_length();
  inline void set_has_width();
  inline void clear_has_width();
  inline void set_has_height();
  inline void clear_has_height();
  inline void set_has_height_segments();
  inline void clear_has_height_segments();
  inline void set_has_radial_segments();
  inline void clear_has_radial_segments();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  float length_;
  float width_;
  float height_;
  ::google::protobuf::uint32 height_segments_;
  ::google::protobuf::uint32 radial_segments_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_generator_2eproto();
  friend void protobuf_AssignDesc_generator_2eproto();
  friend void protobuf_ShutdownFile_generator_2eproto();

  void InitAsDefaultInstance();
  static Config* default_instance_;
};
// ===================================================================


// ===================================================================

// Config

// optional float length = 1;
inline bool Config::has_length() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Config::set_has_length() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Config::clear_has_length() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Config::clear_length() {
  length_ = 0;
  clear_has_length();
}
inline float Config::length() const {
  return length_;
}
inline void Config::set_length(float value) {
  set_has_length();
  length_ = value;
}

// optional float width = 2;
inline bool Config::has_width() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Config::set_has_width() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Config::clear_has_width() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Config::clear_width() {
  width_ = 0;
  clear_has_width();
}
inline float Config::width() const {
  return width_;
}
inline void Config::set_width(float value) {
  set_has_width();
  width_ = value;
}

// optional float height = 3;
inline bool Config::has_height() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Config::set_has_height() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Config::clear_has_height() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Config::clear_height() {
  height_ = 0;
  clear_has_height();
}
inline float Config::height() const {
  return height_;
}
inline void Config::set_height(float value) {
  set_has_height();
  height_ = value;
}

// optional uint32 height_segments = 4;
inline bool Config::has_height_segments() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Config::set_has_height_segments() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Config::clear_has_height_segments() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Config::clear_height_segments() {
  height_segments_ = 0u;
  clear_has_height_segments();
}
inline ::google::protobuf::uint32 Config::height_segments() const {
  return height_segments_;
}
inline void Config::set_height_segments(::google::protobuf::uint32 value) {
  set_has_height_segments();
  height_segments_ = value;
}

// optional uint32 radial_segments = 5;
inline bool Config::has_radial_segments() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Config::set_has_radial_segments() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Config::clear_has_radial_segments() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Config::clear_radial_segments() {
  radial_segments_ = 0u;
  clear_has_radial_segments();
}
inline ::google::protobuf::uint32 Config::radial_segments() const {
  return radial_segments_;
}
inline void Config::set_radial_segments(::google::protobuf::uint32 value) {
  set_has_radial_segments();
  radial_segments_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace generator

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_generator_2eproto__INCLUDED
