// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: editor_settings.proto

#ifndef PROTOBUF_editor_5fsettings_2eproto__INCLUDED
#define PROTOBUF_editor_5fsettings_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace editor {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_editor_5fsettings_2eproto();
void protobuf_AssignDesc_editor_5fsettings_2eproto();
void protobuf_ShutdownFile_editor_5fsettings_2eproto();

class Settings;

// ===================================================================

class Settings : public ::google::protobuf::Message {
 public:
  Settings();
  virtual ~Settings();

  Settings(const Settings& from);

  inline Settings& operator=(const Settings& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Settings& default_instance();

  void Swap(Settings* other);

  // implements Message ----------------------------------------------

  Settings* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Settings& from);
  void MergeFrom(const Settings& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 ticker_height = 1 [default = 50];
  inline bool has_ticker_height() const;
  inline void clear_ticker_height();
  static const int kTickerHeightFieldNumber = 1;
  inline ::google::protobuf::uint32 ticker_height() const;
  inline void set_ticker_height(::google::protobuf::uint32 value);

  // optional uint32 ticker_interval = 2 [default = 20];
  inline bool has_ticker_interval() const;
  inline void clear_ticker_interval();
  static const int kTickerIntervalFieldNumber = 2;
  inline ::google::protobuf::uint32 ticker_interval() const;
  inline void set_ticker_interval(::google::protobuf::uint32 value);

  // optional uint32 ticks_per_interval = 3 [default = 4];
  inline bool has_ticks_per_interval() const;
  inline void clear_ticks_per_interval();
  static const int kTicksPerIntervalFieldNumber = 3;
  inline ::google::protobuf::uint32 ticks_per_interval() const;
  inline void set_ticks_per_interval(::google::protobuf::uint32 value);

  // optional uint32 module_row_height = 4 [default = 50];
  inline bool has_module_row_height() const;
  inline void clear_module_row_height();
  static const int kModuleRowHeightFieldNumber = 4;
  inline ::google::protobuf::uint32 module_row_height() const;
  inline void set_module_row_height(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:editor.Settings)
 private:
  inline void set_has_ticker_height();
  inline void clear_has_ticker_height();
  inline void set_has_ticker_interval();
  inline void clear_has_ticker_interval();
  inline void set_has_ticks_per_interval();
  inline void clear_has_ticks_per_interval();
  inline void set_has_module_row_height();
  inline void clear_has_module_row_height();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 ticker_height_;
  ::google::protobuf::uint32 ticker_interval_;
  ::google::protobuf::uint32 ticks_per_interval_;
  ::google::protobuf::uint32 module_row_height_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_editor_5fsettings_2eproto();
  friend void protobuf_AssignDesc_editor_5fsettings_2eproto();
  friend void protobuf_ShutdownFile_editor_5fsettings_2eproto();

  void InitAsDefaultInstance();
  static Settings* default_instance_;
};
// ===================================================================


// ===================================================================

// Settings

// optional uint32 ticker_height = 1 [default = 50];
inline bool Settings::has_ticker_height() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Settings::set_has_ticker_height() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Settings::clear_has_ticker_height() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Settings::clear_ticker_height() {
  ticker_height_ = 50u;
  clear_has_ticker_height();
}
inline ::google::protobuf::uint32 Settings::ticker_height() const {
  return ticker_height_;
}
inline void Settings::set_ticker_height(::google::protobuf::uint32 value) {
  set_has_ticker_height();
  ticker_height_ = value;
}

// optional uint32 ticker_interval = 2 [default = 20];
inline bool Settings::has_ticker_interval() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Settings::set_has_ticker_interval() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Settings::clear_has_ticker_interval() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Settings::clear_ticker_interval() {
  ticker_interval_ = 20u;
  clear_has_ticker_interval();
}
inline ::google::protobuf::uint32 Settings::ticker_interval() const {
  return ticker_interval_;
}
inline void Settings::set_ticker_interval(::google::protobuf::uint32 value) {
  set_has_ticker_interval();
  ticker_interval_ = value;
}

// optional uint32 ticks_per_interval = 3 [default = 4];
inline bool Settings::has_ticks_per_interval() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Settings::set_has_ticks_per_interval() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Settings::clear_has_ticks_per_interval() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Settings::clear_ticks_per_interval() {
  ticks_per_interval_ = 4u;
  clear_has_ticks_per_interval();
}
inline ::google::protobuf::uint32 Settings::ticks_per_interval() const {
  return ticks_per_interval_;
}
inline void Settings::set_ticks_per_interval(::google::protobuf::uint32 value) {
  set_has_ticks_per_interval();
  ticks_per_interval_ = value;
}

// optional uint32 module_row_height = 4 [default = 50];
inline bool Settings::has_module_row_height() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Settings::set_has_module_row_height() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Settings::clear_has_module_row_height() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Settings::clear_module_row_height() {
  module_row_height_ = 50u;
  clear_has_module_row_height();
}
inline ::google::protobuf::uint32 Settings::module_row_height() const {
  return module_row_height_;
}
inline void Settings::set_module_row_height(::google::protobuf::uint32 value) {
  set_has_module_row_height();
  module_row_height_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace editor

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_editor_5fsettings_2eproto__INCLUDED
