// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: editor_styles.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "editor_styles.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace editor {
namespace protocol {

namespace {

const ::google::protobuf::Descriptor* Style_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Style_reflection_ = NULL;
const ::google::protobuf::Descriptor* Styles_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Styles_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_editor_5fstyles_2eproto() {
  protobuf_AddDesc_editor_5fstyles_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "editor_styles.proto");
  GOOGLE_CHECK(file != NULL);
  Style_descriptor_ = file->message_type(0);
  static const int Style_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Style, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Style, fill_color_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Style, outline_color_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Style, outline_thickness_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Style, font_style_),
  };
  Style_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Style_descriptor_,
      Style::default_instance_,
      Style_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Style, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Style, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Style));
  Styles_descriptor_ = file->message_type(1);
  static const int Styles_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Styles, styles_),
  };
  Styles_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Styles_descriptor_,
      Styles::default_instance_,
      Styles_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Styles, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Styles, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Styles));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_editor_5fstyles_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Style_descriptor_, &Style::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Styles_descriptor_, &Styles::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_editor_5fstyles_2eproto() {
  delete Style::default_instance_;
  delete Style_reflection_;
  delete Styles::default_instance_;
  delete Styles_reflection_;
}

void protobuf_AddDesc_editor_5fstyles_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::editor::protocol::protobuf_AddDesc_editor_5fsettings_2eproto();
  ::common::protocol::protobuf_AddDesc_common_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023editor_styles.proto\022\017editor.protocol\032\025"
    "editor_settings.proto\032\014common.proto\"\242\001\n\005"
    "Style\022\n\n\002id\030\001 \001(\t\022+\n\nfill_color\030\002 \001(\0132\027."
    "common.protocol.Color4\022.\n\routline_color\030"
    "\003 \001(\0132\027.common.protocol.Color4\022\034\n\021outlin"
    "e_thickness\030\004 \001(\002:\0010\022\022\n\nfont_style\030\005 \001(\r"
    "\"0\n\006Styles\022&\n\006styles\030\001 \003(\0132\026.editor.prot"
    "ocol.Style", 290);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "editor_styles.proto", &protobuf_RegisterTypes);
  Style::default_instance_ = new Style();
  Styles::default_instance_ = new Styles();
  Style::default_instance_->InitAsDefaultInstance();
  Styles::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_editor_5fstyles_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_editor_5fstyles_2eproto {
  StaticDescriptorInitializer_editor_5fstyles_2eproto() {
    protobuf_AddDesc_editor_5fstyles_2eproto();
  }
} static_descriptor_initializer_editor_5fstyles_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Style::kIdFieldNumber;
const int Style::kFillColorFieldNumber;
const int Style::kOutlineColorFieldNumber;
const int Style::kOutlineThicknessFieldNumber;
const int Style::kFontStyleFieldNumber;
#endif  // !_MSC_VER

Style::Style()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Style::InitAsDefaultInstance() {
  fill_color_ = const_cast< ::common::protocol::Color4*>(&::common::protocol::Color4::default_instance());
  outline_color_ = const_cast< ::common::protocol::Color4*>(&::common::protocol::Color4::default_instance());
}

Style::Style(const Style& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Style::SharedCtor() {
  _cached_size_ = 0;
  id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  fill_color_ = NULL;
  outline_color_ = NULL;
  outline_thickness_ = 0;
  font_style_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Style::~Style() {
  SharedDtor();
}

void Style::SharedDtor() {
  if (id_ != &::google::protobuf::internal::kEmptyString) {
    delete id_;
  }
  if (this != default_instance_) {
    delete fill_color_;
    delete outline_color_;
  }
}

void Style::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Style::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Style_descriptor_;
}

const Style& Style::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_editor_5fstyles_2eproto();
  return *default_instance_;
}

Style* Style::default_instance_ = NULL;

Style* Style::New() const {
  return new Style;
}

void Style::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_id()) {
      if (id_ != &::google::protobuf::internal::kEmptyString) {
        id_->clear();
      }
    }
    if (has_fill_color()) {
      if (fill_color_ != NULL) fill_color_->::common::protocol::Color4::Clear();
    }
    if (has_outline_color()) {
      if (outline_color_ != NULL) outline_color_->::common::protocol::Color4::Clear();
    }
    outline_thickness_ = 0;
    font_style_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Style::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->id().data(), this->id().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_fill_color;
        break;
      }

      // optional .common.protocol.Color4 fill_color = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_fill_color:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_fill_color()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_outline_color;
        break;
      }

      // optional .common.protocol.Color4 outline_color = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_outline_color:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_outline_color()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(37)) goto parse_outline_thickness;
        break;
      }

      // optional float outline_thickness = 4 [default = 0];
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_outline_thickness:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &outline_thickness_)));
          set_has_outline_thickness();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_font_style;
        break;
      }

      // optional uint32 font_style = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_font_style:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &font_style_)));
          set_has_font_style();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Style::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->id().data(), this->id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->id(), output);
  }

  // optional .common.protocol.Color4 fill_color = 2;
  if (has_fill_color()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->fill_color(), output);
  }

  // optional .common.protocol.Color4 outline_color = 3;
  if (has_outline_color()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->outline_color(), output);
  }

  // optional float outline_thickness = 4 [default = 0];
  if (has_outline_thickness()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->outline_thickness(), output);
  }

  // optional uint32 font_style = 5;
  if (has_font_style()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->font_style(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Style::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->id().data(), this->id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->id(), target);
  }

  // optional .common.protocol.Color4 fill_color = 2;
  if (has_fill_color()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->fill_color(), target);
  }

  // optional .common.protocol.Color4 outline_color = 3;
  if (has_outline_color()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->outline_color(), target);
  }

  // optional float outline_thickness = 4 [default = 0];
  if (has_outline_thickness()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->outline_thickness(), target);
  }

  // optional uint32 font_style = 5;
  if (has_font_style()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->font_style(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Style::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->id());
    }

    // optional .common.protocol.Color4 fill_color = 2;
    if (has_fill_color()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->fill_color());
    }

    // optional .common.protocol.Color4 outline_color = 3;
    if (has_outline_color()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->outline_color());
    }

    // optional float outline_thickness = 4 [default = 0];
    if (has_outline_thickness()) {
      total_size += 1 + 4;
    }

    // optional uint32 font_style = 5;
    if (has_font_style()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->font_style());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Style::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Style* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Style*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Style::MergeFrom(const Style& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_fill_color()) {
      mutable_fill_color()->::common::protocol::Color4::MergeFrom(from.fill_color());
    }
    if (from.has_outline_color()) {
      mutable_outline_color()->::common::protocol::Color4::MergeFrom(from.outline_color());
    }
    if (from.has_outline_thickness()) {
      set_outline_thickness(from.outline_thickness());
    }
    if (from.has_font_style()) {
      set_font_style(from.font_style());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Style::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Style::CopyFrom(const Style& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Style::IsInitialized() const {

  return true;
}

void Style::Swap(Style* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(fill_color_, other->fill_color_);
    std::swap(outline_color_, other->outline_color_);
    std::swap(outline_thickness_, other->outline_thickness_);
    std::swap(font_style_, other->font_style_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Style::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Style_descriptor_;
  metadata.reflection = Style_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Styles::kStylesFieldNumber;
#endif  // !_MSC_VER

Styles::Styles()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Styles::InitAsDefaultInstance() {
}

Styles::Styles(const Styles& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Styles::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Styles::~Styles() {
  SharedDtor();
}

void Styles::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Styles::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Styles::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Styles_descriptor_;
}

const Styles& Styles::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_editor_5fstyles_2eproto();
  return *default_instance_;
}

Styles* Styles::default_instance_ = NULL;

Styles* Styles::New() const {
  return new Styles;
}

void Styles::Clear() {
  styles_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Styles::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .editor.protocol.Style styles = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_styles:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_styles()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_styles;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Styles::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .editor.protocol.Style styles = 1;
  for (int i = 0; i < this->styles_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->styles(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Styles::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .editor.protocol.Style styles = 1;
  for (int i = 0; i < this->styles_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->styles(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Styles::ByteSize() const {
  int total_size = 0;

  // repeated .editor.protocol.Style styles = 1;
  total_size += 1 * this->styles_size();
  for (int i = 0; i < this->styles_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->styles(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Styles::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Styles* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Styles*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Styles::MergeFrom(const Styles& from) {
  GOOGLE_CHECK_NE(&from, this);
  styles_.MergeFrom(from.styles_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Styles::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Styles::CopyFrom(const Styles& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Styles::IsInitialized() const {

  return true;
}

void Styles::Swap(Styles* other) {
  if (other != this) {
    styles_.Swap(&other->styles_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Styles::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Styles_descriptor_;
  metadata.reflection = Styles_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace editor

// @@protoc_insertion_point(global_scope)
